### ISSUE TITLE
EC2 Instance main.py run log

### ISSUE THREAD

**Issue by xinfinn** [oozliuoo/WineApp#22]
[ec2-user@ip-172-31-47-66 VivinoParser]$ pwd
/home/ec2-user/wineapp/Winery/VivinoParser
[ec2-user@ip-172-31-47-66 VivinoParser]$ sudo python main.py 
/usr/local/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ec2-user/wineapp/Winery/VivinoParser/pkg/Parsers.py", line 352, in parseGrapeProc
    description = self.parseDescription(soup);
  File "/home/ec2-user/wineapp/Winery/VivinoParser/pkg/Parsers.py", line 459, in parseDescription
    if (descriptionNode.find(class_="grape-origin")):
  File "/usr/local/lib/python2.7/site-packages/bs4/element.py", line 1234, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/bs4/element.py", line 1255, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/bs4/element.py", line 529, in _find_all
    i = next(generator)
  File "/usr/local/lib/python2.7/site-packages/bs4/element.py", line 1273, in descendants
    current = current.next_element
AttributeError: 'NoneType' object has no attribute 'next_element'

{"origin": {"districts": ["California", "South Coast"], "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-us1x.png", "2x": "/Resources/Img/Flag/icon-flag-us2x.png"}, "flagClass": "icon-flag-us"}, "name": "United States"}}, "name": "Temecula Valley Gew\u00fcrztraminer", "grapes": [], "query": "temecula-valley-gewurztraminer-2012", "vintageList": [{"currency": "USD", "avg_price": "8.00", "thumbnail": "//images.vivino.com/thumbs/1364777523_3784_375x500.jpg", "year": "2012"}, {"currency": "", "avg_price": "-", "thumbnail": "//images.vivino.com/thumbs/01qcguhtyh160_375x500.jpg", "year": "2011"}, {"currency": "", "avg_price": "-", "thumbnail": "//images.vivino.com/thumbs/01uslg7xrowuf_375x500.jpg", "year": "2010"}], "foodPairing": ["Rich fish (salmon, tuna etc)", "Spicy food", "Sweet desserts", "Poultry", "Mild and soft cheese"], "thumbnail": "//images.vivino.com/thumbs/1364777523_3784_375x500.jpg"}
[ec2-user@ip-172-31-47-66 VivinoParser]$

**Comment by xinfinn** [comment]
On my local machine, however:

60f81dc9eb3c:VivinoParser mrfeng$ python main.py 
{"origin": {"districts": ["California", "South Coast"], "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-us1x.png", "2x": "/Resources/Img/Flag/icon-flag-us2x.png"}, "flagClass": "icon-flag-us"}, "name": "United States"}}, "name": "Temecula Valley Gew\u00fcrztraminer", "grapes": [{"origin": {"country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-fr1x.png", "2x": "/Resources/Img/Flag/icon-flag-fr2x.png"}, "flagClass": "icon-flag-fr"}, "name": "France"}, "district": "Alsace"}, "name": "Gewurztraminer", "originatesFrom": [], "alsoKnownAs": [], "mostlyUsedIn": [{"usage": "13%", "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-de1x.png", "2x": "/Resources/Img/Flag/icon-flag-de2x.png"}, "flagClass": "icon-flag-de"}, "name": "Germany"}}, {"usage": "49%", "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-fr1x.png", "2x": "/Resources/Img/Flag/icon-flag-fr2x.png"}, "flagClass": "icon-flag-fr"}, "name": "France"}}, {"usage": "7%", "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-it1x.png", "2x": "/Resources/Img/Flag/icon-flag-it2x.png"}, "flagClass": "icon-flag-it"}, "name": "Italy"}}, {"usage": "13%", "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-us1x.png", "2x": "/Resources/Img/Flag/icon-flag-us2x.png"}, "flagClass": "icon-flag-us"}, "name": "United States"}}], "query": "gewurztraminer", "foodPairing": ["Rich fish (salmon, tuna etc)", "Spicy food", "Sweet desserts", "Poultry", "Mild and soft cheese"], "mostlyUsedFor": {"White": "85 %", "Red": "9 %"}, "description": "Lychee, rose petals, honey and orange blossom\n\nGewurztraminer is a pink wine grape producing distinct whites, rich in aroma and flowery\u00a0perfume and with a wonderful deep color. The flavor associations of lychee, gingerbread,\u00a0vanilla, grapefruit, rose petals and honeysuckle come out of this varietal.\n\n\n\nGewurztraminer origins from Alsace, but today it is grown in countries such as Italy, Spain, Austria and even Chile. The name stems from the village Traminer in the North Italian Alto Adige, and \u00a0the German word \u2018Gew\u00fcrz\u00b4 for spice.\n\n\n\n\nThe full and flowery aroma can be mistaken for being too sweet, but the good ones have a long, dry finish. Though Gewurztraminer is easily recognizable and great for beginners, it is also a complex grape loved by connoisseurs of all kinds. Popular Gewurztraminer wines include Agustinos Bio-Bio Valley Reserve Limited Editions Gewurztraminer\u00a0and \u00a0Vin D Alsace Gewurztraminer Reserve.\n\n\n\n\nEnjoy on its own, with soft, stinky cheeses or pair carefully with Asian flavored dishes or citrusy seafood \u2013 or be bold and serve with pork-based sausages."}], "query": "temecula-valley-gewurztraminer-2012", "vintageList": [{"currency": "", "avg_price": "-", "thumbnail": "//images.vivino.com/thumbs/01uslg7xrowuf_375x500.jpg", "year": "2010"}, {"currency": "USD", "avg_price": "8.00", "thumbnail": "//images.vivino.com/thumbs/1364777523_3784_375x500.jpg", "year": "2012"}, {"currency": "", "avg_price": "-", "thumbnail": "//images.vivino.com/thumbs/01qcguhtyh160_375x500.jpg", "year": "2011"}], "foodPairing": ["Rich fish (salmon, tuna etc)", "Spicy food", "Sweet desserts", "Poultry", "Mild and soft cheese"], "thumbnail": "//images.vivino.com/thumbs/1364777523_3784_375x500.jpg"}

**Comment by xinfinn** [comment]
60f81dc9eb3c:VivinoParser mrfeng$ python main.py
/Library/Python/2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
^[[B{"origin": {"districts": ["California", "South Coast"], "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-us1x.png", "2x": "/Resources/Img/Flag/icon-flag-us2x.png"}, "flagClass": "icon-flag-us"}, "name": "United States"}}, "name": "Temecula Valley Gew\u00fcrztraminer", "grapes": [{"origin": {"country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-fr1x.png", "2x": "/Resources/Img/Flag/icon-flag-fr2x.png"}, "flagClass": "icon-flag-fr"}, "name": "France"}, "district": "Alsace"}, "name": "Gewurztraminer", "originatesFrom": [], "alsoKnownAs": [], "mostlyUsedIn": [{"usage": "13%", "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-de1x.png", "2x": "/Resources/Img/Flag/icon-flag-de2x.png"}, "flagClass": "icon-flag-de"}, "name": "Germany"}}, {"usage": "49%", "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-fr1x.png", "2x": "/Resources/Img/Flag/icon-flag-fr2x.png"}, "flagClass": "icon-flag-fr"}, "name": "France"}}, {"usage": "7%", "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-it1x.png", "2x": "/Resources/Img/Flag/icon-flag-it2x.png"}, "flagClass": "icon-flag-it"}, "name": "Italy"}}, {"usage": "13%", "country": {"flag": {"links": {"1x": "/Resources/Img/Flag/icon-flag-us1x.png", "2x": "/Resources/Img/Flag/icon-flag-us2x.png"}, "flagClass": "icon-flag-us"}, "name": "United States"}}], "query": "gewurztraminer", "foodPairing": ["Rich fish (salmon, tuna etc)", "Spicy food", "Sweet desserts", "Poultry", "Mild and soft cheese"], "mostlyUsedFor": {"White": "85 %", "Red": "9 %"}, "description": "Gewurztraminer"}], "query": "temecula-valley-gewurztraminer-2012", "vintageList": [{"currency": "USD", "avg_price": "8.00", "thumbnail": "//images.vivino.com/thumbs/1364777523_3784_375x500.jpg", "year": "2012"}, {"currency": "", "avg_price": "-", "thumbnail": "//images.vivino.com/thumbs/01qcguhtyh160_375x500.jpg", "year": "2011"}, {"currency": "", "avg_price": "-", "thumbnail": "//images.vivino.com/thumbs/01uslg7xrowuf_375x500.jpg", "year": "2010"}], "foodPairing": ["Rich fish (salmon, tuna etc)", "Spicy food", "Sweet desserts", "Poultry", "Mild and soft cheese"], "thumbnail": "//images.vivino.com/thumbs/1364777523_3784_375x500.jpg"}

**Comment by xinfinn** [comment]
force bs4 version=4.3.2 fix this issue
